{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base=ContentObjectAttribute}
<select name="{$attribute_base}_ymccountry_iso_3166_3_{$attribute.id}">
<option value=""></option>
{foreach $attribute.content.available_countries as $iso => $-name-}
<option value="{$iso}"{if eq($attribute.content.iso-3166-3,$iso)} selected="selected"{/if}>{$-name-|i18n("kernel/content/datatypes/ymccountry")}</option>
{/foreach}
</select>
{/default}
