{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base="ContentObjectAttribute"}
{if $attribute.class_content.is_node_placement}
  {def $input_name='ymcActiveNodeAssignmentsPool[]'}
  {foreach $attribute.class_content.options as $option}
    <input type="hidden" name="ymcNodeAssignmentsPool[]" value="{$option.identifier}" />
  {/foreach}
{else}
  {def $input_name=concat($attribute_base,'_ymcenhancedselection_selected_array_',$attribute.id,'[]')}
{/if}
{let selected_id_array=$attribute.content}

{if $attribute.class_content.is_multiselect}
  {foreach $attribute.class_content.options as $option}
    <span class="nobreak">
      <input type="checkbox" name="{$input_name}"
             value="{$option.identifier}" {if $selected_id_array|contains($option.identifier)}checked="checked"{/if} />
              {$option.name|wash( xhtml )}&nbsp;&nbsp;
    </span>
  {/foreach}
  <input type="hidden" name="{$input_name}" value="0" />
{else}
  <select name="{$input_name}">
    {if $attribute.has_content|not()}
      <option value="">{'--Nothing selected--'|i18n('kernel/classes/datatypes')}</option>
    {elseif $attribute.is_required|not()}
      <option value="">{'--Nothing--'|i18n('kernel/classes/datatypes')}</option>
    {/if}
    {foreach $attribute.class_content.options as $option}
      <option value="{$option.identifier}" {if $selected_id_array|contains($option.identifier)}selected="selected"{/if}>
        {$option.name|wash(xhtml)}
      </option>
    {/foreach}
  </select>
{/if}

{section show=$attribute.contentclass_attribute.is_required}
    <span class="required_field">*</span>
{/section}
{/let}
{/default}
