{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base=ContentObjectAttribute}

<table>
 <tr>
  <td><label>{"Nameserver"|i18n("design/standard/content/datatype")}</label>
      <input type="text" name="{$attribute_base}_soarecord_ns_{$attribute.id}" size="20" value="{$attribute.content.nameserver}" />&nbsp;
  </td>
  <td><label>{"Email"|i18n("design/standard/content/datatype")}</label>
      <input type="text" name="{$attribute_base}_soarecord_email_{$attribute.id}" size="20" value="{$attribute.content.email}" />
  </td>
 </tr>
 <tr>
  <td><label>{"Refresh period"|i18n("design/standard/content/datatype")}</label>
      <input type="text" name="{$attribute_base}_soarecord_refresh_period_{$attribute.id}" size="10" value="{$attribute.content.refresh_period}" />
  </td>
  <td><label>{"Retry interval"|i18n("design/standard/content/datatype")}</label>
      <input type="text" name="{$attribute_base}_soarecord_retry_interval_{$attribute.id}" size="10" value="{$attribute.content.retry_interval}" />
  </td>
 </tr>
 <tr>
  <td><label>{"Expire time"|i18n("design/standard/content/datatype")}</label>
      <input type="text" name="{$attribute_base}_soarecord_expire_time_{$attribute.id}" size="10" value="{$attribute.content.expire_time}" />
  </td>
  <td><label>{"Default ttl"|i18n("design/standard/content/datatype")}</label>
      <input type="text" name="{$attribute_base}_soarecord_default_ttl_{$attribute.id}" size="10" value="{$attribute.content.default_ttl}" />
  </td>
 </tr>
</table>

{/default}