{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base=ContentObjectAttribute}
{let selected_id_array=$attribute.content
     break_on=3
     break=0}

{section show=$attribute.class_content.is_multiselect}
<table>
<tr>
{section var=Options loop=$attribute.class_content.options}
 {section show=eq($break,$break_on)}
  {set break=1}
  </tr>
  <tr>
 {section-else}
  {set break=sum($break,1)}
 {/section}
<td><p><input type="checkbox" name="{$attribute_base}_ezselect_selected_array_{$attribute.id}[]" value="{$Options.item.id}" {section show=$selected_id_array|contains( $Options.item.id )}checked="checked"{/section} />{$Options.item.name|wash( xhtml )}&nbsp;&nbsp;</p></td>
{/section}
</tr>
</table>
<input type="hidden" name="{$attribute_base}_ezselect_selected_array_{$attribute.id}[]" value=" " />

{section-else}
<select name="{$attribute_base}_ezselect_selected_array_{$attribute.id}[]">
{section var=Options loop=$attribute.class_content.options}
<option value="{$Options.item.id}" {section show=$selected_id_array|contains( $Options.item.id )}selected="selected"{/section}>{$Options.item.name|wash( xhtml )}</option>
{/section}
</select>


{/section}

{/let}
{/default}