{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base=ContentObjectAttribute}
<input class="smallbox" type="text" name="{$attribute_base}_data_float_{$attribute.id}" size="12" value="{section show=$attribute.has_http_value}{$attribute.value}{section-else}{$attribute.content.content}{/section}" />

<select name="{$attribute_base}_unit_{$attribute.id}">
    <option value="cuin">cubic inch (cu in)</option>
    <option value="cuft">cubic foot (cu ft)</option>
    <option value="cuyd">cubic yard (cu yd)</option>
    <option  value="pintukliquid">pint (UK liquid)</option>
    <option  value="quartukliquid">quart (UK liquid)</option>
    <option  value="gallonukliquid">gallon (UK liquid)</option>
    <option  value="pintusliquid">pint (US liquid)</option>
    <option  value="quartusliquid">quart (US liquid)</option>
    <option value="gallonusliquid">gallon (US liquid)</option>
    <option value="ml">Milliliter (ml)</option>
    <option value="l" selected="selected">Liter (l)</option>
    <option value="hl">Hektoliter (hl)</option>
    <option value="m3">Kubikmeter (m^3)</option>
    <option value="oil">barrel (oil)</option>
    <option value="RT">Brutto-Registertonne (RT)</option>
    <option value="oceanton">ocean ton</option>
</select>


{/default}