{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base=ContentObjectAttribute}
<input class="smallbox" type="text" name="{$attribute_base}_data_float_{$attribute.id}" size="12" value="{section show=$attribute.has_http_value}{$attribute.value}{section-else}{$attribute.content.content}{/section}" />

<select name="{$attribute_base}_unit_{$attribute.id}">
    <option value="mg">Milligramm (mg)</option>
    <option value="Kt">Karat (metr., Kt)</option>
    <option value="g">Gramm (g)</option>
    <option value="kg" selected="selected">Kilogramm (kg)</option>
    <option value="t">Tonne (t)</option>
    <option value="dr">Dram (dr)</option>
    <option value="oz">ounce (oz)</option>
    <option value="lb">Pound (lb)</option>
    <option value="cwt">hundredweight (cwt)</option>
    <option value="scwt">short cwt</option>
    <option value="ston">short ton</option>
    <option value="lton">long ton</option>
</select>


{/default}