{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base='ContentClass'
         html_class='full'}
<p>Dieser Text wird dem User beim Bearbeiten angezeigt.</p>

<textarea id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$class_attribute.contentclassattribute_id}_{$class_attribute.contentclass_attribute_identifier}" class="{eq( $html_class, 'half' )|choose( 'box', 'halfbox' )} ezcc-{$class_attribute.object.content_class.identifier} ezcca-{$class_attribute.object.content_class.identifier}_{$class_attribute.contentclass_attribute_identifier}" name="{$attribute_base}_data_text_{$class_attribute.id}" cols="70" rows="5">{$class_attribute.content|wash}</textarea>
{/default}
