{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div class="block">
    <label>{'Subdomains erlauben'|i18n( 'design/standard/class/datatype' )}</label>
    <input type="checkbox" name="ContentClass_ezdomain_with_subdomain_value_{$class_attribute.id}" {section show=eq($class_attribute.data_int1,1)}checked="checked"{/section} value="1" />
</div>
<input type="hidden" name="ContentClass_ezdomain_with_subdomain_switch_{$class_attribute.id}" value="enabled" />

