{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div class="block">
    <label>{'Subdomains erlauben'|i18n( 'design/standard/class/datatype' )}:</label>
    <p>{section show=eq($class_attribute.data_int1,1)}Ja{section-else}Nein{/section}</p>
</div>

