{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{let messengers=hash( "aim", "AOL Instant Messenger"|i18n( 'design/standard/class/datatype' ),
                      "icq", "ICQ"|i18n( 'design/standard/class/datatype' ),
                      "msn", "MSN Messenger"|i18n( 'design/standard/class/datatype' ),
                      "skype", "Skype"|i18n( 'design/standard/class/datatype' ),
                      "yahoo", "Yahoo Messenger"|i18n( 'design/standard/class/datatype' ) ) }
<div class="block">
<table>
 <tr>
  <td><label>{'Messenger'|i18n( 'design/standard/class/datatype' )}</label>
      <p>{$messengers[$class_attribute.data_text1]}</p>
  </td>
  <td><label>{'Max record age in seconds'|i18n( 'design/standard/class/datatype' )}</label>
      <p>{$class_attribute.data_int1}</p>
  </td>
 </tr>
</table>
</div>
{/let}
