{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div class="block">
<label>{'Voreinstellungen für neue Objekte'|i18n( 'design/standard/class/datatype' )}</label>
<table>
 <tr>
  <td><label>{"Nameserver"|i18n("design/standard/content/datatype")}</label>
      <p>{$class_attribute.data_text1}</p>
  </td>
  <td><label>{"Email"|i18n("design/standard/content/datatype")}</label>
      <p>{$class_attribute.data_text2}</p>
  </td>
 </tr>
 <tr>
  <td><label>{"Refresh period"|i18n("design/standard/content/datatype")}</label>
      <p>{$class_attribute.data_int1}</p>
  </td>
  <td><label>{"Retry interval"|i18n("design/standard/content/datatype")}</label>
      <p>{$class_attribute.data_int2}</p>
  </td>
 </tr>
 <tr>
  <td><label>{"Expire time"|i18n("design/standard/content/datatype")}</label>
      <p>{$class_attribute.data_int3}</p>
  </td>
  <td><label>{"Default ttl"|i18n("design/standard/content/datatype")}</label>
      <p>{$class_attribute.data_int4}</p>
  </td>
 </tr>
</table>
</div>
