<?php 
return array (
  'ymcDatatypeForm' => './interfaces/form.php',
  'TestDatatypeCallbackFilterIntLeadingZero' => './tests/tests_callback_filter/int_leading_zero_test.php',
  'ReadOptionXmlTest' => './tests/tests_datatype_enhanced_selection/read_option_xml_test.php',
  'OptionArrayToXmlTest' => './tests/tests_datatype_enhanced_selection/option_array_to_xml_test.php',
  'ymcDatatypeDomain' => './datatypes/ymcdomain/ymcdomaintype.php',
  'ymcDatatypeSoaRecordType' => './datatypes/ymcsoarecord/ymcsoarecordtype.php',
  'ymcDatatypeDateClassForm' => './datatypes/ymcdate/classform.php',
  'ymcDatatypeDateObjectForm' => './datatypes/ymcdate/objectform.php',
  'ymcDatatypeDateType' => './datatypes/ymcdate/ymcdatetype.php',
  'ymcDatatypeDate' => './datatypes/ymcdate/ymcdate.php',
  'ymcDatatypeIpv4Type' => './datatypes/ymcipv4/ymcipv4type.php',
  'ymcDatatypeEnhancedSelectionClassForm' => './datatypes/ymcenhancedselection/classform.php',
  'ymcDatatypeEnhancedSelectionObjectForm' => './datatypes/ymcenhancedselection/objectform.php',
  'ymcDatatypeEnhancedSelectionClassContent' => './datatypes/ymcenhancedselection/class_content.php',
  'ymcDatatypeEnhancedSelectionType' => './datatypes/ymcenhancedselection/ymcenhancedselectiontype.php',
  'ymcDatatypeVolumeType' => './datatypes/ymcvolume/ymcvolumetype.php',
  'ymcDatatypeNumberAsStringType' => './datatypes/ymcnumberasstring/ymcnumberasstringtype.php',
  'ymcDatatypeUniqueStringType' => './datatypes/ymcuniquestring/ymcuniquestringtype.php',
  'ymcDatatypeMschapv2Type' => './datatypes/ymcmschapv2/ymcmschapv2type.php',
  'ymcDatatypeInstantMessengerClassForm' => './datatypes/ymcinstantmessenger/classform.php',
  'ymcDatatypeInstantMessengerType' => './datatypes/ymcinstantmessenger/ymcinstantmessengertype.php',
  'ymcDatatypeInstantMessenger' => './datatypes/ymcinstantmessenger/ymcinstantmessenger.php',
  'ymcDatatypeDateTimeClassForm' => './datatypes/ymcdatetime/classform.php',
  'ymcDatatypeDateTime' => './datatypes/ymcdatetime/ymcdatetime.php',
  'ymcDatatypeDateTimeObjectForm' => './datatypes/ymcdatetime/objectform.php',
  'ymcDatatypeDateTimeType' => './datatypes/ymcdatetime/ymcdatetimetype.php',
  'ymcDatatypeFilterIntLeadingZero' => './filter_callbacks/int_leading_zero.php',
  'ymcDatatypeException' => './exceptions/ymcdatatype.php',
  'ymcDatatypeInvalidParams' => './exceptions/invalid_params.php',
  'ymcDatatypeEditHooks' => './ymc_edit_hooks.php',
);
?>